### ISSUE TITLE
potential enhancements

### ISSUE THREAD

**Issue by remdragon** [dandclark/BigInt#6]
I like your library, it's simple and easy to understand, but I found a few things that I would like to improve about it. If you're interested in the following enhancements, I'd be happy to fork and create a PR, but some of these changes will require breaking the API:

* extra conversion support for unsigned integers
* ability to convert BigInt to a string buffer
* small performance improvement to BigInt_print() and BigInt_fprint() and code deduplication
* fix bugs failing to check for malloc() returning NULL
* import safe_math_impl.h from safe_math library and use it to verify whether conversion from BigInt to integer was successful
* fix potential (albeit unlikely) infinite loop bug in several places if big_int->num_digits > max signed int value (since num_digits is unsigned)

**Comment by remdragon** [comment]
also just found a minor bug assuming sizeof(char) == 1

**Comment by dandclark** [comment]
Hi @remdragon, these all seem like good improvements! I'd be happy to review PRs for any of these contributions.

It'll probably be easier for me to review and merge as separate smaller PRs rather than one big one since a lot of these things are not necessarily related.

**Comment by remdragon** [comment]
yeah I was also thinking it should be more than one PR. I'll start with the more obviously important things like bugs & security fixes. Thanks!
